# Generated by Django 4.2.4 on 2023-08-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_rename_scopes_article_tags_alter_scope_articles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='articles',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tags',
            new_name='tag',
        ),
    ]
